import numpy as np
import matplotlib.pyplot as plt
import os

# ==========================================
# PUBLICATION FORMATTING
# ==========================================
plt.rcParams.update({
    'font.size': 14,
    'axes.linewidth': 1.5,
    'xtick.major.width': 1.5,
    'ytick.major.width': 1.5,
    'xtick.direction': 'in',
    'ytick.direction': 'in',
    'lines.linewidth': 2.5,
    'lines.markersize': 6
})

def plot_dynamics_scaling():
    """
    Reads the single 3D tensor master file and plots S(t) vs t 
    for all available system sizes (L) at the simulated probability (p).
    """
    # 1. Point this explicitly to the file generated by run_dynamics.py
    file_path = "../data/mipt_dynamics_L128_shots_500.npz"
    target_p = 0.02  # The probability you want to look at
    
    print(f"Loading data from {file_path}...")
    
    if not os.path.exists(file_path):
        print(f"CRITICAL ERROR: File not found at {file_path}")
        print("Make sure you run your dynamics simulation first!")
        return

    # 2. Extract the data arrays
    data = np.load(file_path)
    L_values = data['L_values']
    p_values = data['p_values']
    time_steps = data['time_steps']
    
    # This is the 3D tensor: Shape is (Number of Ls, Number of ps, Number of Timesteps)
    S_mean_master = data['S_mean_master'] 
    
    # 3. Find the exact matrix index for the requested probability
    p_idx = (np.abs(p_values - target_p)).argmin()
    actual_p = p_values[p_idx]
    
    # 4. Set up the plot
    fig, ax = plt.subplots(figsize=(8, 6), dpi=150)
    colors = plt.cm.viridis(np.linspace(0, 0.9, len(L_values)))
    
    # 5. Loop through L and slice the 3D tensor
    for i, L in enumerate(L_values):
        
        # Extract the 1D line as usual
        entropy_vs_time = S_mean_master[i, p_idx, :]
        
        # SLICE TO REMOVE HALF-STEPS
        # This grabs every second element, showing only full brick-wall cycles
        ax.plot(time_steps[::2], entropy_vs_time[::2], label=f'L = {L}', color=colors[i])

    # 6. Formatting and saving
    ax.set_title(f'Entanglement Growth Scaling ($p = {actual_p:.3f}$)', pad=15)
    ax.set_xlabel('Time ($t$)', fontsize=16)
    ax.set_ylabel('Entanglement Entropy $S(t)$', fontsize=16)
    ax.legend(loc='lower right', frameon=False)
    ax.grid(True, linestyle='--', alpha=0.6)
    
    os.makedirs("../figures", exist_ok=True)
    save_path = f"../figures/mipt_dynamics_scaling_p{actual_p:.2f}.pdf"
    plt.savefig(save_path, bbox_inches='tight')
    plt.close()
    
    print(f"-> Success! Plot saved to {save_path}")

if __name__ == '__main__':
    plot_dynamics_scaling()